baseURL = 'https://ciber127.github.io/cyberSoul-blog/'
languageCode = 'es'
title = 'CyberSoul - El Futuro Digital'
theme = 'PaperMod'

[params]

  googleAnalytics = "G-PH1TP4SQSM"
  description = "Explorando IA, Ciberseguridad y Tecnologías del Futuro"
  author = "CyberSoul Team"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = "Bienvenido a CyberSoul 🚀"
  Content = "Explorando el futuro digital a través de IA, ciberseguridad y tecnologías emergentes"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/cybersoul"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Ciber127"

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  
  [[menu.main]]
    name = "Categorías"
    url = "/categories/"
    weight = 3
  
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
