baseURL = "https://Ciber127.github.io/cyberSoul-blog/"
languageCode = "es-co"
title = "CyberSoul 2026"
theme = "PaperMod"  # o el nombre exacto de tu tema

[params]
  author = "CIBERSEGURDAD"
  description = "Consejos prácticos de ciberseguridad"

[menu]
  [[menu.main]]
    identifier = "inicio"
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 2
